version: "3.0"
services:
  api:
    container_name: api
    build: .
    image: "api"
    ports:
      - "8088:80"
    links:
      - "redis"
    environment:
      - API_SERVER_ADDR=:80
      - REDIS_ADDR=redis:6379
      - REDIS_DB=0

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
