---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: api
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 0.02
            memory: 50Mi
          requests:
            cpu: 0.01
            memory: 10Mi
        env:
        - name: API_SERVER_ADDR
          value: ":80"
        - name: REDIS_ADDR
          value: "redis:6379"
        - name: REDIS_DB
          value: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: default
  labels:
    app: api
spec:
  selector:
    app: api
  type: ClusterIP
  ports:
  - port: 8088
    targetPort: 80
    protocol: TCP
    name: http
